"""empty message

Revision ID: 2b6623e65957
Revises: 3250a5a6e456
Create Date: 2021-04-17 16:55:50.265373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6623e65957'
down_revision = '3250a5a6e456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('year', sa.String(length=255), nullable=True))
    op.drop_column('cars', 'years')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cars', 'year')
    # ### end Alembic commands ###
